In [1]:
import pandas as pd
import numpy as np

movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [2]:
movies=pd.read_csv('tmdb_5000_movies.csv') 
credits=pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
movies.shape

(4803, 20)

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
credits.shape

(4803, 4)

In [7]:
movies=movies.merge(credits,on='title')

In [8]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
movies.shape

(4809, 23)

In [10]:
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

movies.head()

In [11]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

### Removing rows having null values

In [12]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [13]:
movies.dropna(inplace=True)

### checking for duplict rows

In [14]:
movies.duplicated().sum()

0

In [15]:
movies['genres']

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...
4804    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4805    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4806    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4807                                                   []
4808                  [{"id": 99, "name": "Documentary"}]
Name: genres, Length: 4806, dtype: object

### Reformating genres,keywords,cast,crew

In [16]:
# convert genres to ["Action"Comedy"...]

In [17]:
import ast #for converting string to list

In [18]:
def convert(obj): #function that maps each genre and extracts name fron each object...
    A=[]
    for x in ast.literal_eval(obj):
        A.append(x['name'])
    return A

In [19]:
movies['genres']=movies['genres'].apply(convert)

In [20]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [21]:
movies['keywords']=movies['keywords'].apply(convert) #similarly filtering keywords

In [22]:
movies['keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united statesâ€“mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [23]:
movies['cast']

0       [{"cast_id": 242, "character": "Jake Sully", "...
1       [{"cast_id": 4, "character": "Captain Jack Spa...
2       [{"cast_id": 1, "character": "James Bond", "cr...
3       [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4       [{"cast_id": 5, "character": "John Carter", "c...
                              ...
4804    [{"cast_id": 1, "character": "El Mariachi", "c...
4805    [{"cast_id": 1, "character": "Buzzy", "credit_...
4806    [{"cast_id": 8, "character": "Oliver O\u2019To...
4807    [{"cast_id": 3, "character": "Sam", "credit_id...
4808    [{"cast_id": 3, "character": "Herself", "credi...
Name: cast, Length: 4806, dtype: object

In [24]:
def convert3(obj):#we will be taking only first 3 names from cast array
    A = []
    counter = 0
    for x in ast.literal_eval(obj):
        if counter != 3:
            A.append(x['name'])
            counter+=1
        else:
            break
    return A

In [25]:
movies['cast']= movies['cast'].apply(convert3)

In [26]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [27]:
def findDir(obj):#extracting names from crew where job is director
    A=[]
    for x in ast.literal_eval(obj):
        if x['job'] =='Director':
            A.append(x['name'])
            break
    return A

In [28]:
movies['crew']=movies['crew'].apply(findDir)

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [30]:
#converting overview from string format to list so that we can concatenate with others
movies['overview']=movies['overview'].apply(lambda x: x.split())

In [31]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

#### Removing spaces

In [32]:
#removing spaces between words Sam Worthington-->SamWorthington
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [33]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

### forming tags

In [34]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [35]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [36]:
#framing new dataset with required columns,now we dont need genres,overview..etc 
#as we have tags.
new_dataset=movies[['movie_id','title','tags']]

In [37]:
new_dataset.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [38]:
#converting list to string so that we can do s=text vectorization.
new_dataset['tags']=new_dataset['tags'].apply(lambda x:" ".join(x))

/tmp/ipykernel_11649/2010674294.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_dataset['tags']=new_dataset['tags'].apply(lambda x:" ".join(x))

In [39]:
new_dataset.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [40]:
#convert tags into lowercase
new_dataset['tags']=new_dataset['tags'].apply(lambda x:x.lower())

/tmp/ipykernel_11649/3509159001.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_dataset['tags']=new_dataset['tags'].apply(lambda x:x.lower())

In [41]:
new_dataset['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

STEMMING OF TAGS

In [42]:
import nltk

In [43]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [44]:
def stem(text):
    y=[]
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [45]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [46]:
new_dataset['tags']=new_dataset['tags'].apply(stem)

/tmp/ipykernel_11649/1283114390.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_dataset['tags']=new_dataset['tags'].apply(stem)

CREATING VECTORS

In [47]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [48]:
vectors = cv.fit_transform(new_dataset['tags']).toarray()

In [49]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [50]:
cv.get_feature_names()

/home/yeshwanth/.local/lib/python3.10/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcÃ­a',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brainwash',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloÃ«gracemoretz',
 'chloÃ«sevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciarÃ¡nhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 ...]

In [51]:
from sklearn.metrics.pairwise import euclidean_distances
distances=euclidean_distances(vectors,vectors)

In [52]:
distances[0]

array([0.        , 8.1240384 , 8.        , ..., 9.2736185 , 9.32737905,
       9.        ])

In [53]:
sorted(list(enumerate(distances[0])),key=lambda x:x[1])

[(0, 0.0),
 (4405, 6.082762530298219),
 (3527, 6.324555320336759),
 (4461, 6.324555320336759),
 (4641, 6.324555320336759),
 (3998, 6.48074069840786),
 (3730, 6.557438524302),
 (4777, 6.557438524302),
 (1444, 6.6332495807108),
 (3550, 6.6332495807108),
 (3634, 6.6332495807108),
 (4097, 6.6332495807108),
 (4293, 6.6332495807108),
 (4636, 6.6332495807108),
 (2232, 6.708203932499369),
 (3919, 6.708203932499369),
 (4246, 6.708203932499369),
 (4253, 6.708203932499369),
 (4348, 6.708203932499369),
 (4793, 6.708203932499369),
 (1276, 6.782329983125268),
 (2432, 6.782329983125268),
 (3025, 6.782329983125268),
 (3082, 6.782329983125268),
 (3507, 6.782329983125268),
 (3552, 6.782329983125268),
 (3720, 6.782329983125268),
 (3787, 6.782329983125268),
 (3923, 6.782329983125268),
 (4053, 6.782329983125268),
 (4281, 6.782329983125268),
 (4494, 6.782329983125268),
 (4502, 6.782329983125268),
 (4533, 6.782329983125268),
 (4596, 6.782329983125268),
 (172, 6.855654600401044),
 (1194, 6.855654600401044),
 (2480, 6.855654600401044),
 (2796, 6.855654600401044),
 (2856, 6.855654600401044),
 (3002, 6.855654600401044),
 (3080, 6.855654600401044),
 (3296, 6.855654600401044),
 (3327, 6.855654600401044),
 (3359, 6.855654600401044),
 (3462, 6.855654600401044),
 (3595, 6.855654600401044),
 (3614, 6.855654600401044),
 (3804, 6.855654600401044),
 (4010, 6.855654600401044),
 (4173, 6.855654600401044),
 (4309, 6.855654600401044),
 (4353, 6.855654600401044),
 (4409, 6.855654600401044),
 (4528, 6.855654600401044),
 (4615, 6.855654600401044),
 (61, 6.928203230275509),
 (649, 6.928203230275509),
 (1075, 6.928203230275509),
 (1272, 6.928203230275509),
 (1530, 6.928203230275509),
 (2007, 6.928203230275509),
 (2255, 6.928203230275509),
 (2331, 6.928203230275509),
 (2376, 6.928203230275509),
 (2466, 6.928203230275509),
 (2511, 6.928203230275509),
 (2529, 6.928203230275509),
 (2544, 6.928203230275509),
 (2674, 6.928203230275509),
 (2850, 6.928203230275509),
 (2880, 6.928203230275509),
 (2914, 6.928203230275509),
 (2999, 6.928203230275509),
 (3083, 6.928203230275509),
 (3229, 6.928203230275509),
 (3393, 6.928203230275509),
 (3497, 6.928203230275509),
 (3888, 6.928203230275509),
 (3969, 6.928203230275509),
 (4036, 6.928203230275509),
 (4126, 6.928203230275509),
 (4315, 6.928203230275509),
 (4516, 6.928203230275509),
 (4551, 6.928203230275509),
 (4587, 6.928203230275509),
 (4617, 6.928203230275509),
 (4753, 6.928203230275509),
 (4757, 6.928203230275509),
 (4802, 6.928203230275509),
 (62, 7.0),
 (151, 7.0),
 (381, 7.0),
 (534, 7.0),
 (1014, 7.0),
 (1321, 7.0),
 (1629, 7.0),
 (1673, 7.0),
 (1698, 7.0),
 (1715, 7.0),
 (1830, 7.0),
 (2237, 7.0),
 (2315, 7.0),
 (2789, 7.0),
 (2974, 7.0),
 (3180, 7.0),
 (3218, 7.0),
 (3268, 7.0),
 (3328, 7.0),
 (3363, 7.0),
 (3656, 7.0),
 (3721, 7.0),
 (3885, 7.0),
 (3978, 7.0),
 (4000, 7.0),
 (4007, 7.0),
 (4062, 7.0),
 (4153, 7.0),
 (4192, 7.0),
 (4278, 7.0),
 (4391, 7.0),
 (4462, 7.0),
 (4537, 7.0),
 (4550, 7.0),
 (4619, 7.0),
 (4621, 7.0),
 (4679, 7.0),
 (4715, 7.0),
 (4737, 7.0),
 (189, 7.0710678118654755),
 (373, 7.0710678118654755),
 (466, 7.0710678118654755),
 (584, 7.0710678118654755),
 (866, 7.0710678118654755),
 (891, 7.0710678118654755),
 (1664, 7.0710678118654755),
 (1882, 7.0710678118654755),
 (1955, 7.0710678118654755),
 (1972, 7.0710678118654755),
 (1984, 7.0710678118654755),
 (2198, 7.0710678118654755),
 (2279, 7.0710678118654755),
 (2339, 7.0710678118654755),
 (2388, 7.0710678118654755),
 (2618, 7.0710678118654755),
 (2654, 7.0710678118654755),
 (2671, 7.0710678118654755),
 (2877, 7.0710678118654755),
 (3006, 7.0710678118654755),
 (3040, 7.0710678118654755),
 (3130, 7.0710678118654755),
 (3146, 7.0710678118654755),
 (3154, 7.0710678118654755),
 (3198, 7.0710678118654755),
 (3275, 7.0710678118654755),
 (3375, 7.0710678118654755),
 (3469, 7.0710678118654755),
 (3546, 7.0710678118654755),
 (3566, 7.0710678118654755),
 (3854, 7.0710678118654755),
 (3938, 7.0710678118654755),
 (3949, 7.0710678118654755),
 (4014, 7.0710678118654755),
 (4026, 7.0710678118654755),
 (4052, 7.0710678118654755),
 (4071, 7.0710678118654755),
 (4081, 7.0710678118654755),
 (4189, 7.0710678118654755),
 (4365, 7.0710678118654755),
 (4492, 7.0710678118654755),
 (4507, 7.0710678118654755),
 (4568, 7.0710678118654755),
 (4654, 7.0710678118654755),
 (4697, 7.0710678118654755),
 (4701, 7.0710678118654755),
 (4784, 7.0710678118654755),
 (251, 7.14142842854285),
 (256, 7.14142842854285),
 (490, 7.14142842854285),
 (776, 7.14142842854285),
 (808, 7.14142842854285),
 (1045, 7.14142842854285),
 (1348, 7.14142842854285),
 (1488, 7.14142842854285),
 (1575, 7.14142842854285),
 (1580, 7.14142842854285),
 (1822, 7.14142842854285),
 (1862, 7.14142842854285),
 (2034, 7.14142842854285),
 (2085, 7.14142842854285),
 (2258, 7.14142842854285),
 (2278, 7.14142842854285),
 (2442, 7.14142842854285),
 (2610, 7.14142842854285),
 (2647, 7.14142842854285),
 (2675, 7.14142842854285),
 (2786, 7.14142842854285),
 (2853, 7.14142842854285),
 (3070, 7.14142842854285),
 (3125, 7.14142842854285),
 (3378, 7.14142842854285),
 (3506, 7.14142842854285),
 (3519, 7.14142842854285),
 (3690, 7.14142842854285),
 (3718, 7.14142842854285),
 (3728, 7.14142842854285),
 (3753, 7.14142842854285),
 (3774, 7.14142842854285),
 (3830, 7.14142842854285),
 (3832, 7.14142842854285),
 (3914, 7.14142842854285),
 (3927, 7.14142842854285),
 (3941, 7.14142842854285),
 (3988, 7.14142842854285),
 (4075, 7.14142842854285),
 (4147, 7.14142842854285),
 (4174, 7.14142842854285),
 (4236, 7.14142842854285),
 (4279, 7.14142842854285),
 (4333, 7.14142842854285),
 (4342, 7.14142842854285),
 (4362, 7.14142842854285),
 (4395, 7.14142842854285),
 (4419, 7.14142842854285),
 (4473, 7.14142842854285),
 (4563, 7.14142842854285),
 (4564, 7.14142842854285),
 (4606, 7.14142842854285),
 (4643, 7.14142842854285),
 (4723, 7.14142842854285),
 (56, 7.211102550927978),
 (200, 7.211102550927978),
 (249, 7.211102550927978),
 (314, 7.211102550927978),
 (495, 7.211102550927978),
 (627, 7.211102550927978),
 (653, 7.211102550927978),
 (850, 7.211102550927978),
 (1005, 7.211102550927978),
 (1042, 7.211102550927978),
 (1139, 7.211102550927978),
 (1193, 7.211102550927978),
 (1201, 7.211102550927978),
 (1254, 7.211102550927978),
 (1270, 7.211102550927978),
 (1327, 7.211102550927978),
 (1377, 7.211102550927978),
 (1382, 7.211102550927978),
 (1409, 7.211102550927978),
 (1524, 7.211102550927978),
 (1621, 7.211102550927978),
 (1761, 7.211102550927978),
 (1845, 7.211102550927978),
 (1922, 7.211102550927978),
 (1989, 7.211102550927978),
 (2011, 7.211102550927978),
 (2061, 7.211102550927978),
 (2084, 7.211102550927978),
 (2104, 7.211102550927978),
 (2165, 7.211102550927978),
 (2178, 7.211102550927978),
 (2242, 7.211102550927978),
 (2274, 7.211102550927978),
 (2353, 7.211102550927978),
 (2568, 7.211102550927978),
 (2712, 7.211102550927978),
 (2749, 7.211102550927978),
 (2861, 7.211102550927978),
 (2870, 7.211102550927978),
 (2891, 7.211102550927978),
 (2975, 7.211102550927978),
 (2977, 7.211102550927978),
 (3098, 7.211102550927978),
 (3156, 7.211102550927978),
 (3159, 7.211102550927978),
 (3185, 7.211102550927978),
 (3202, 7.211102550927978),
 (3269, 7.211102550927978),
 (3288, 7.211102550927978),
 (3430, 7.211102550927978),
 (3477, 7.211102550927978),
 (3496, 7.211102550927978),
 (3529, 7.211102550927978),
 (3726, 7.211102550927978),
 (3733, 7.211102550927978),
 (3781, 7.211102550927978),
 (3957, 7.211102550927978),
 (3966, 7.211102550927978),
 (4041, 7.211102550927978),
 (4118, 7.211102550927978),
 (4139, 7.211102550927978),
 (4165, 7.211102550927978),
 (4186, 7.211102550927978),
 (4212, 7.211102550927978),
 (4243, 7.211102550927978),
 (4300, 7.211102550927978),
 (4375, 7.211102550927978),
 (4415, 7.211102550927978),
 (4515, 7.211102550927978),
 (4555, 7.211102550927978),
 (4583, 7.211102550927978),
 (4601, 7.211102550927978),
 (4651, 7.211102550927978),
 (4708, 7.211102550927978),
 (4718, 7.211102550927978),
 (4736, 7.211102550927978),
 (4742, 7.211102550927978),
 (4763, 7.211102550927978),
 (94, 7.280109889280518),
 (205, 7.280109889280518),
 (476, 7.280109889280518),
 (505, 7.280109889280518),
 (668, 7.280109889280518),
 (774, 7.280109889280518),
 (800, 7.280109889280518),
 (897, 7.280109889280518),
 (935, 7.280109889280518),
 (972, 7.280109889280518),
 (995, 7.280109889280518),
 (1028, 7.280109889280518),
 (1033, 7.280109889280518),
 (1166, 7.280109889280518),
 (1183, 7.280109889280518),
 (1323, 7.280109889280518),
 (1360, 7.280109889280518),
 (1437, 7.280109889280518),
 (1464, 7.280109889280518),
 (1501, 7.280109889280518),
 (1521, 7.280109889280518),
 (1630, 7.280109889280518),
 (1745, 7.280109889280518),
 (1770, 7.280109889280518),
 (1868, 7.280109889280518),
 (1879, 7.280109889280518),
 (1901, 7.280109889280518),
 (1907, 7.280109889280518),
 (1939, 7.280109889280518),
 (1969, 7.280109889280518),
 (1986, 7.280109889280518),
 (2161, 7.280109889280518),
 (2205, 7.280109889280518),
 (2326, 7.280109889280518),
 (2417, 7.280109889280518),
 (2530, 7.280109889280518),
 (2551, 7.280109889280518),
 (2634, 7.280109889280518),
 (2708, 7.280109889280518),
 (2724, 7.280109889280518),
 (2725, 7.280109889280518),
 (2780, 7.280109889280518),
 (2801, 7.280109889280518),
 (2896, 7.280109889280518),
 (3019, 7.280109889280518),
 (3049, 7.280109889280518),
 (3063, 7.280109889280518),
 (3069, 7.280109889280518),
 (3117, 7.280109889280518),
 (3126, 7.280109889280518),
 (3426, 7.280109889280518),
 (3505, 7.280109889280518),
 (3528, 7.280109889280518),
 (3531, 7.280109889280518),
 (3613, 7.280109889280518),
 (3623, 7.280109889280518),
 (3775, 7.280109889280518),
 (3829, 7.280109889280518),
 (3889, 7.280109889280518),
 (3970, 7.280109889280518),
 (3982, 7.280109889280518),
 (4011, 7.280109889280518),
 (4076, 7.280109889280518),
 (4135, 7.280109889280518),
 (4248, 7.280109889280518),
 (4261, 7.280109889280518),
 (4266, 7.280109889280518),
 (4400, 7.280109889280518),
 (4412, 7.280109889280518),
 (4517, 7.280109889280518),
 (4542, 7.280109889280518),
 (4572, 7.280109889280518),
 (4628, 7.280109889280518),
 (4635, 7.280109889280518),
 (4637, 7.280109889280518),
 (4646, 7.280109889280518),
 (4655, 7.280109889280518),
 (4738, 7.280109889280518),
 (4764, 7.280109889280518),
 (4771, 7.280109889280518),
 (31, 7.3484692283495345),
 (105, 7.3484692283495345),
 (179, 7.3484692283495345),
 (218, 7.3484692283495345),
 (233, 7.3484692283495345),
 (489, 7.3484692283495345),
 (539, 7.3484692283495345),
 (624, 7.3484692283495345),
 (699, 7.3484692283495345),
 (739, 7.3484692283495345),
 (892, 7.3484692283495345),
 (1010, 7.3484692283495345),
 (1041, 7.3484692283495345),
 (1104, 7.3484692283495345),
 (1275, 7.3484692283495345),
 (1288, 7.3484692283495345),
 (1329, 7.3484692283495345),
 (1373, 7.3484692283495345),
 (1478, 7.3484692283495345),
 (1489, 7.3484692283495345),
 (1502, 7.3484692283495345),
 (1577, 7.3484692283495345),
 (1599, 7.3484692283495345),
 (1613, 7.3484692283495345),
 (1655, 7.3484692283495345),
 (1710, 7.3484692283495345),
 (1923, 7.3484692283495345),
 (1956, 7.3484692283495345),
 (2038, 7.3484692283495345),
 (2040, 7.3484692283495345),
 (2043, 7.3484692283495345),
 (2114, 7.3484692283495345),
 (2212, 7.3484692283495345),
 (2297, 7.3484692283495345),
 (2317, 7.3484692283495345),
 (2323, 7.3484692283495345),
 (2332, 7.3484692283495345),
 (2378, 7.3484692283495345),
 (2381, 7.3484692283495345),
 (2390, 7.3484692283495345),
 (2456, 7.3484692283495345),
 (2479, 7.3484692283495345),
 (2515, 7.3484692283495345),
 (2521, 7.3484692283495345),
 (2534, 7.3484692283495345),
 (2584, 7.3484692283495345),
 (2621, 7.3484692283495345),
 (2677, 7.3484692283495345),
 (2685, 7.3484692283495345),
 (2764, 7.3484692283495345),
 (2772, 7.3484692283495345),
 (3055, 7.3484692283495345),
 (3072, 7.3484692283495345),
 (3081, 7.3484692283495345),
 (3103, 7.3484692283495345),
 (3119, 7.3484692283495345),
 (3128, 7.3484692283495345),
 (3155, 7.3484692283495345),
 (3178, 7.3484692283495345),
 (3217, 7.3484692283495345),
 (3281, 7.3484692283495345),
 (3325, 7.3484692283495345),
 (3350, 7.3484692283495345),
 (3425, 7.3484692283495345),
 (3483, 7.3484692283495345),
 (3513, 7.3484692283495345),
 (3525, 7.3484692283495345),
 (3579, 7.3484692283495345),
 (3621, 7.3484692283495345),
 (3716, 7.3484692283495345),
 (3758, 7.3484692283495345),
 (3833, 7.3484692283495345),
 (3839, 7.3484692283495345),
 (3870, 7.3484692283495345),
 (3896, 7.3484692283495345),
 (3918, 7.3484692283495345),
 (3962, 7.3484692283495345),
 (3976, 7.3484692283495345),
 (4001, 7.3484692283495345),
 (4033, 7.3484692283495345),
 (4060, 7.3484692283495345),
 (4130, 7.3484692283495345),
 (4368, 7.3484692283495345),
 (4390, 7.3484692283495345),
 (4428, 7.3484692283495345),
 (4431, 7.3484692283495345),
 (4441, 7.3484692283495345),
 (4443, 7.3484692283495345),
 (4457, 7.3484692283495345),
 (4477, 7.3484692283495345),
 (4557, 7.3484692283495345),
 (4577, 7.3484692283495345),
 (4747, 7.3484692283495345),
 (4750, 7.3484692283495345),
 (4758, 7.3484692283495345),
 (4765, 7.3484692283495345),
 (4792, 7.3484692283495345),
 (134, 7.416198487095663),
 (260, 7.416198487095663),
 (357, 7.416198487095663),
 (368, 7.416198487095663),
 (558, 7.416198487095663),
 (719, 7.416198487095663),
 (763, 7.416198487095663),
 (780, 7.416198487095663),
 (865, 7.416198487095663),
 (914, 7.416198487095663),
 (966, 7.416198487095663),
 (967, 7.416198487095663),
 (1021, 7.416198487095663),
 (1209, 7.416198487095663),
 (1240, 7.416198487095663),
 (1246, 7.416198487095663),
 (1385, 7.416198487095663),
 (1410, 7.416198487095663),
 (1413, 7.416198487095663),
 (1421, 7.416198487095663),
 (1528, 7.416198487095663),
 (1582, 7.416198487095663),
 (1665, 7.416198487095663),
 (1757, 7.416198487095663),
 (1774, 7.416198487095663),
 (1778, 7.416198487095663),
 (1791, 7.416198487095663),
 (2136, 7.416198487095663),
 (2312, 7.416198487095663),
 (2369, 7.416198487095663),
 (2445, 7.416198487095663),
 (2597, 7.416198487095663),
 (2608, 7.416198487095663),
 (2731, 7.416198487095663),
 (2762, 7.416198487095663),
 (2778, 7.416198487095663),
 (2854, 7.416198487095663),
 (2862, 7.416198487095663),
 (2935, 7.416198487095663),
 (2966, 7.416198487095663),
 (3021, 7.416198487095663),
 (3038, 7.416198487095663),
 (3077, 7.416198487095663),
 (3167, 7.416198487095663),
 (3223, 7.416198487095663),
 (3234, 7.416198487095663),
 (3303, 7.416198487095663),
 (3397, 7.416198487095663),
 (3447, 7.416198487095663),
 (3564, 7.416198487095663),
 (3663, 7.416198487095663),
 (3694, 7.416198487095663),
 (3769, 7.416198487095663),
 (3954, 7.416198487095663),
 (3985, 7.416198487095663),
 (3999, 7.416198487095663),
 (4040, 7.416198487095663),
 (4044, 7.416198487095663),
 (4066, 7.416198487095663),
 (4093, 7.416198487095663),
 (4108, 7.416198487095663),
 (4131, 7.416198487095663),
 (4231, 7.416198487095663),
 (4378, 7.416198487095663),
 (4407, 7.416198487095663),
 (4447, 7.416198487095663),
 (4460, 7.416198487095663),
 (4548, 7.416198487095663),
 (4573, 7.416198487095663),
 (4594, 7.416198487095663),
 (4638, 7.416198487095663),
 (4796, 7.416198487095663),
 (4797, 7.416198487095663),
 (35, 7.483314773547883),
 (157, 7.483314773547883),
 (220, 7.483314773547883),
 (319, 7.483314773547883),
 (325, 7.483314773547883),
 (336, 7.483314773547883),
 (382, 7.483314773547883),
 (465, 7.483314773547883),
 (487, 7.483314773547883),
 (598, 7.483314773547883),
 (715, 7.483314773547883),
 (748, 7.483314773547883),
 (773, 7.483314773547883),
 (797, 7.483314773547883),
 (858, 7.483314773547883),
 (906, 7.483314773547883),
 (1077, 7.483314773547883),
 (1078, 7.483314773547883),
 (1280, 7.483314773547883),
 (1308, 7.483314773547883),
 (1330, 7.483314773547883),
 (1424, 7.483314773547883),
 (1495, 7.483314773547883),
 (1737, 7.483314773547883),
 (1769, 7.483314773547883),
 (1773, 7.483314773547883),
 (1789, 7.483314773547883),
 (1826, 7.483314773547883),
 (1884, 7.483314773547883),
 (1925, 7.483314773547883),
 (1998, 7.483314773547883),
 (2010, 7.483314773547883),
 (2053, 7.483314773547883),
 (2282, 7.483314773547883),
 (2299, 7.483314773547883),
 (2394, 7.483314773547883),
 (2407, 7.483314773547883),
 (2427, 7.483314773547883),
 (2533, 7.483314773547883),
 (2548, 7.483314773547883),
 (2553, 7.483314773547883),
 (2573, 7.483314773547883),
 (2585, 7.483314773547883),
 (2640, 7.483314773547883),
 (2691, 7.483314773547883),
 (2754, 7.483314773547883),
 (2812, 7.483314773547883),
 (2872, 7.483314773547883),
 (2913, 7.483314773547883),
 (2925, 7.483314773547883),
 (2970, 7.483314773547883),
 (3124, 7.483314773547883),
 (3219, 7.483314773547883),
 (3282, 7.483314773547883),
 (3335, 7.483314773547883),
 (3465, 7.483314773547883),
 (3555, 7.483314773547883),
 (3563, 7.483314773547883),
 (3578, 7.483314773547883),
 (3627, 7.483314773547883),
 (3863, 7.483314773547883),
 (3871, 7.483314773547883),
 (3891, 7.483314773547883),
 (3972, 7.483314773547883),
 (3996, 7.483314773547883),
 (4018, 7.483314773547883),
 (4030, 7.483314773547883),
 (4056, 7.483314773547883),
 (4140, 7.483314773547883),
 (4149, 7.483314773547883),
 (4198, 7.483314773547883),
 (4219, 7.483314773547883),
 (4242, 7.483314773547883),
 (4282, 7.483314773547883),
 (4290, 7.483314773547883),
 (4321, 7.483314773547883),
 (4332, 7.483314773547883),
 (4346, 7.483314773547883),
 (4394, 7.483314773547883),
 (4411, 7.483314773547883),
 (4463, 7.483314773547883),
 (4474, 7.483314773547883),
 (4490, 7.483314773547883),
 (4496, 7.483314773547883),
 (4554, 7.483314773547883),
 (4660, 7.483314773547883),
 (4746, 7.483314773547883),
 (4749, 7.483314773547883),
 (4767, 7.483314773547883),
 (33, 7.54983443527075),
 (100, 7.54983443527075),
 (148, 7.54983443527075),
 (209, 7.54983443527075),
 (263, 7.54983443527075),
 (308, 7.54983443527075),
 (418, 7.54983443527075),
 (435, 7.54983443527075),
 (483, 7.54983443527075),
 (498, 7.54983443527075),
 (537, 7.54983443527075),
 (570, 7.54983443527075),
 (577, 7.54983443527075),
 (613, 7.54983443527075),
 (669, 7.54983443527075),
 (878, 7.54983443527075),
 (913, 7.54983443527075),
 (931, 7.54983443527075),
 (973, 7.54983443527075),
 (1026, 7.54983443527075),
 (1096, 7.54983443527075),
 (1153, 7.54983443527075),
 (1156, 7.54983443527075),
 (1158, 7.54983443527075),
 (1228, 7.54983443527075),
 (1292, 7.54983443527075),
 (1300, 7.54983443527075),
 (1314, 7.54983443527075),
 (1328, 7.54983443527075),
 (1350, 7.54983443527075),
 (1393, 7.54983443527075),
 (1466, 7.54983443527075),
 (1476, 7.54983443527075),
 (1601, 7.54983443527075),
 (1618, 7.54983443527075),
 (1670, 7.54983443527075),
 (1696, 7.54983443527075),
 (1727, 7.54983443527075),
 (1779, 7.54983443527075),
 (1782, 7.54983443527075),
 (1807, 7.54983443527075),
 (1860, 7.54983443527075),
 (1942, 7.54983443527075),
 (1947, 7.54983443527075),
 (2000, 7.54983443527075),
 (2076, 7.54983443527075),
 (2118, 7.54983443527075),
 (2218, 7.54983443527075),
 (2335, 7.54983443527075),
 (2416, 7.54983443527075),
 (2426, 7.54983443527075),
 (2435, 7.54983443527075),
 (2457, 7.54983443527075),
 (2518, 7.54983443527075),
 (2581, 7.54983443527075),
 (2614, 7.54983443527075),
 (2622, 7.54983443527075),
 (2623, 7.54983443527075),
 (2637, 7.54983443527075),
 (2652, 7.54983443527075),
 (2656, 7.54983443527075),
 (2664, 7.54983443527075),
 (2694, 7.54983443527075),
 (2698, 7.54983443527075),
 (2737, 7.54983443527075),
 (2743, 7.54983443527075),
 (2779, 7.54983443527075),
 (2783, 7.54983443527075),
 (2787, 7.54983443527075),
 (2808, 7.54983443527075),
 (2844, 7.54983443527075),
 (2855, 7.54983443527075),
 (2893, 7.54983443527075),
 (3177, 7.54983443527075),
 (3243, 7.54983443527075),
 (3290, 7.54983443527075),
 (3398, 7.54983443527075),
 (3413, 7.54983443527075),
 (3420, 7.54983443527075),
 (3488, 7.54983443527075),
 (3510, 7.54983443527075),
 (3548, 7.54983443527075),
 (3567, 7.54983443527075),
 (3625, 7.54983443527075),
 (3642, 7.54983443527075),
 (3661, 7.54983443527075),
 (3678, 7.54983443527075),
 (3711, 7.54983443527075),
 (3846, 7.54983443527075),
 (3971, 7.54983443527075),
 (4025, 7.54983443527075),

In [54]:
def recommend(movie):
    movie_index=new_dataset[new_dataset['title']== movie].index[0]
    node_distances=distances[movie_index]
    recommended_list=sorted(list(enumerate(node_distances)),key=lambda x:x[1])[0:6]
    temp=[];
    for i in recommended_list:
            temp.append(new_dataset.iloc[i[0]].title)
    return temp

In [55]:
new_dataset.title

0                                         Avatar
1       Pirates of the Caribbean: At World's End
2                                        Spectre
3                          The Dark Knight Rises
4                                    John Carter
                          ...
4804                                 El Mariachi
4805                                   Newlyweds
4806                   Signed, Sealed, Delivered
4807                            Shanghai Calling
4808                           My Date with Drew
Name: title, Length: 4806, dtype: object

In [56]:
recommend("Avatar")

['Avatar',
 'The Helix... Loaded',
 'Khiladi 786',
 'Harrison Montgomery',
 "Amidst the Devil's Wings",
 'Sardaarji']

In [57]:
recommend("avatar")

IndexError: index 0 is out of bounds for axis 0 with size 0

In [58]:
recommend("Avatar")

['Avatar',
 'The Helix... Loaded',
 'Khiladi 786',
 'Harrison Montgomery',
 "Amidst the Devil's Wings",
 'Sardaarji']

In [59]:
recommend("Sardaarji")

['Journey to Saturn',
 'The Helix... Loaded',
 'Khiladi 786',
 'Harrison Montgomery',
 "Amidst the Devil's Wings",
 'Space Pirate Captain Harlock']

In [60]:
recommend("John Carter")

['John Carter',
 'The Helix... Loaded',
 'Khiladi 786',
 'Harrison Montgomery',
 "Amidst the Devil's Wings",
 'Devil']

In [61]:
recommend("El Mariachi")

['Shanghai Calling',
 'Harrison Montgomery',
 'The Salon',
 'The Helix... Loaded',
 'Khiladi 786',
 'The Loss of Sexual Innocence']

In [62]:
recommend("The Salon")

['Forty Shades of Blue',
 'Harrison Montgomery',
 "Amidst the Devil's Wings",
 'The Helix... Loaded',
 'Khiladi 786',
 'The Ten']

In [63]:
recommend("Khiladi 786")

['[REC]Â²',
 'The Helix... Loaded',
 'Khiladi 786',
 'Harrison Montgomery',
 "Amidst the Devil's Wings",
 'The Lords of Salem']

In [64]:
recommend("The Ten")

['A Room for Romeo Brass',
 'The Inkwell',
 'The Helix... Loaded',
 'Khiladi 786',
 'Harrison Montgomery',
 "Amidst the Devil's Wings"]